### ISSUE TITLE
Criação do banco de dados - [4]

### ISSUE THREAD

**Issue by JohnnyBaptista** [EJComp-Unesp/Dvora-Backend#1]
Primeiramente será preciso criar o banco de dados para a aplicação.

Precisa-se responder essa questão:
- Qual tipo de banco será usado?

Tarefas:
- [x] Criar o banco de dados
- [ ] Criar um relatório explicativo sobre o banco (explicando as entidades e como se relacionam ou não)

**Comment by LeoYudi** [comment]
Link para Visualização do modelo ER

https://drive.google.com/open?id=1a9tx2CLe58QU9sVj1wJ-6-JJ3wIhORf9
