### ISSUE TITLE
Token do delete do membro

### ISSUE THREAD

**Issue by JohnnyBaptista** [EJComp-Unesp/Dvora-Backend#29]
Está sendo pedido um token do nível de membro para o usuário, em vez do nível EJ. É preciso alterar isto

**Comment by LeoYudi** [comment]
Na branch develop, arquivo de routes.js, linha 41, já está a autenticação de empresa júnior, da uma olhada.

**Comment by JohnnyBaptista** [comment]
@LeoYudi, qual a situação dessa issue, foi resolvido?

**Comment by LeoYudi** [comment]
Acredito que foi, na rota de delete do membro pede token de ej
