### ISSUE TITLE
Alterar Tabela da EJ

### ISSUE THREAD

**Issue by JohnnyBaptista** [EJComp-Unesp/Dvora-Backend#30]
A tabela agora deve ter uma relação com a tabela de diretoria

**Comment by viniciusveu** [comment]
O que tem que alterar na tabela da EJ? Não é apenas ter o ID da EJ na tabela da Diretoria?

**Comment by JohnnyBaptista** [comment]
Na verdade, não estou lembrando o que discutimos, porque acho q diretoria e EJ acho q não tem relação. Na verdade é só membro e diretoria mesmo.
@LeoYudi , o que vc pensa?

**Comment by JohnnyBaptista** [comment]
foi alterado?
