### ISSUE TITLE
Criar Tabela de Diretoria

### ISSUE THREAD

**Issue by JohnnyBaptista** [EJComp-Unesp/Dvora-Backend#32]
A tabela será para armazenar as respectivas diretorias de cada EJ.
Deve conter os dados de nome e ID
E ser relacionada aos membros e EJs

**Comment by viniciusveu** [comment]
Na tabela de membro possui o campo 'STRING board', tenho que alterar para int e referenciar para o ID na tabela de board correto?

**Comment by JohnnyBaptista** [comment]
> Na tabela de membro possui o campo 'STRING board', tenho que alterar para int e referenciar para o ID na tabela de board correto?

correto
