### ISSUE TITLE
Plantão TEM feedback

### ISSUE THREAD

**Issue by JohnnyBaptista** [EJComp-Unesp/Dvora-Backend#44]
A tabela de plantão tem que ter um id de feedback relacionado a ele, pois assim conseguimos associar se o acompanhamento foi feito ou não.

**Comment by JohnnyBaptista** [comment]
@LeoYudi @viniciusveu

**Comment by LeoYudi** [comment]
O innerjoin nao funciona sem esse id na tabela de plantao? Se nao funciona eh uma boa. Ae ficaria a fk no feedback e no plantao, certo?

**Comment by JohnnyBaptista** [comment]
Mas então vc faria um inner join em alguma rota específica?
Acho q não faria muito sentido, não consigo ver implementação disso, principalmente por fazer sentido "um plantão **TEM** um feedback" relacionado a ele.
Atualmente a relação de feedback e plantão é como?

**Comment by LeoYudi** [comment]
Nos gets de plantão que forem necessarios  eu faria o inner join, nao acho que precise criar uma nova rota. A relação de feedback e plantão é 1 para 1

**Comment by JohnnyBaptista** [comment]
Ahh sim, então só precisamos de um get específico para os feedbacks por EJ?
Tipo, na tela de feedback precisamos que apareça os membros da EJ e se o plantão foi feito e se o acompanhamento foi feito. Aí como poderíamos contornar isso?
![image](https://user-images.githubusercontent.com/27309546/85087935-3c794980-b1b5-11ea-8e30-8ae0d4c996cb.png)

**Comment by LeoYudi** [comment]
Se o acompanhamento for do plantao da semana, da pra ve se o feedback tem como acompanhamento nulo ou nao, ae define esse isfeedbackdone como true ou false.

**Comment by LeoYudi** [comment]
Na tabela mostra se o membro deu o feedback dele ? Pq se nao tiver o feedback dele nao tem acompanhamento

**Comment by etakao** [comment]
Que eu me lembre não tem esse status do feedback do membro, só do plantão e do monitoramento mesmo.

**Comment by JohnnyBaptista** [comment]
> Na tabela mostra se o membro deu o feedback dele ? Pq se nao tiver o feedback dele nao tem acompanhamento

Então se o feedback for `null` significa que não foi feito o acompanhamento?

**Comment by LeoYudi** [comment]
Acredito que sim. Acho que a implementação não vai ser mt complicada.

**Comment by JohnnyBaptista** [comment]
Então precisamos apenas de uma rota que retorne os feedbacks por EJ.
```javascript
[
  {
    "name": "Leonardo Yogurte",
    "duties": []
  },
  {
    "name": "Maluane Stafocher",
    "duties": []
  },
  {
    "name": "yudi",
    "duties": [
      {
        "elapsedTime": 172913,
        "feedback": null
      },
      {
        "elapsedTime": 0,
        "feedback": null
      }
    ]
  }
]
```
Vejam se faz sentido:
Tendo esse retorno da pra saber já que se os `duties` forem = `[ ]`, então o acompanhamento e plantão não foram feito. Se `duties` tiver objetos dentro dele, então basta checar se o feedback for = `null` para saber se foi feito ou não o acompanhamento.
Faz sentido? Está muito difícil?

**Comment by etakao** [comment]
Faz sentido sim @JohnnyBaptista

**Comment by etakao** [comment]
ou na verdade, vou ver a documentação aqui

**Comment by JohnnyBaptista** [comment]
PR #49
