### ISSUE TITLE
Retorno caso senha esteja incorreta

### ISSUE THREAD

**Issue by JohnnyBaptista** [EJComp-Unesp/Dvora-Backend#47]
Ao bater o plantão e a senha estiver incorreta, retornar erro 400

**Comment by viniciusveu** [comment]
`if (!validPassword(password, member.password))
        return res.status(400).json({ error: 'INCORRECT PASSWORD' });`
Eu não entendi bem o que tem que arrumar. Do jeito que está ele já retorna o erro 400.

**Comment by viniciusveu** [comment]
@JohnnyBaptista
