### ISSUE TITLE
Alterações na documentação

### ISSUE THREAD

**Issue by JohnnyBaptista** [EJComp-Unesp/Dvora-Backend#68]
- Alteração na rota index do feedback => /feedback/{jeId}

- No retorno da rota index, agora existe uma verificação se o feedback foi respondido ou não, ficando como retorno para o isMonitoringDone:
0 -> não feito
1 -> feito
2 -> membro não respondeu 

- Alteração na rota getMemberDuties => /member/{memberId}/feedback

- Colocar parte de diretorias na documentação - falar com @viniciusveu 
- Na parte das diretorias, alterou também o create de membros, passando o `boardId`

**Comment by GSushi** [comment]
https://dvoradocumentation.netlify.app/
