### ISSUE TITLE
Usuário que não fechou o plantão antes do dia acabar não consegue iniciar um novo plantão

### ISSUE THREAD

**Issue by JohnnyBaptista** [EJComp-Unesp/Dvora-Backend#82]
![image](https://user-images.githubusercontent.com/27309546/89363486-b5b9f680-d6a6-11ea-841b-27bf0100494f.png)

Ao tentar iniciar um novo plantão, tendo um que não havia sido fechado no dia anterior, ele me retornou um 409 com a mensagem "plantão já iniciado".

Isso precisa ser alterado para que, caso o dia já tenha terminado e algum plantão ainda estiver ativo, retorne apenas esses plantões que não haviam sido fechados

https://github.com/EJComp-Unesp/Dvora-Backend/blob/13166c3f7200235a0336db8a8de3816753fe3bd2/src/controllers/DutyController.js#L38

No método `consult` deve haver alguma verificação se ainda tem plantões abertos e retorna-los

**Comment by viniciusveu** [comment]
Além de retornar em consult() os plantões que não foram fechados, deve finalizá-los em algum lugar? Ou retornar um erro mais específico falando que um plantão ainda está aberto de algum dia anterior?

**Comment by JohnnyBaptista** [comment]
> [ @JohnnyBaptista ] Além de retornar em consult() os plantões que não foram fechados, deve finalizá-los em algum lugar? Ou retornar um erro mais específico falando que um plantão ainda está aberto de algum dia anterior?

O certo é apenas retornar todos os plantões abertos até o momento, não necessariamente sendo daquele dia

**Comment by LeoYudi** [comment]
Vou fazer a query completa para não precisar utilizar o for
