### ISSUE TITLE
Verificação dos plantões do dia errada?

### ISSUE THREAD

**Issue by JohnnyBaptista** [EJComp-Unesp/Dvora-Backend#86]
Talvez a checagem de do período dos plantões para retornar apenas os do dia esteja errada.
Ao criar o plantão as 23h do dia 09/10 ele ainda foi retornado no dia seguinte as 19h.
Verificar a possibilidade desse bug

**Comment by LeoYudi** [comment]
jp, sabe me dizer se a rota eh do consult dos plantões ou se eh do get geral do feedback?

**Comment by JohnnyBaptista** [comment]
> jp, sabe me dizer se a rota eh do consult dos plantões ou se eh do get geral do feedback?

consult

**Comment by JohnnyBaptista** [comment]
essa issue estava relacionada ao PR #90 ??
