### ISSUE TITLE
Ordenar plantões

### ISSUE THREAD

**Issue by LeoYudi** [EJComp-Unesp/Dvora-Backend#89]
Os plantões da tela de membro não estão sendo enviados de forma ordenada.

**Comment by JohnnyBaptista** [comment]
Acredito que se utilizar o método `.sort()` do array antes de enviar a resposta basta.
A não ser que seja possível fazer por query, ai recomendaria essa solução

**Comment by LeoYudi** [comment]
estou tentando fazer por query, mas nao ta funcionando, nao sei o que estou fazendo de errado
